### ISSUE TITLE
Hydration error with nextjs and react 18

### ISSUE THREAD

**Issue by max-frai** [tienphaw/figma-squircle#1]
Hello, thank you for amazing library. After upgrade to latest packages the problem with hydration appeared:

`Warning: Prop style did not match. Server: ... Client: ...`

I generated diff and here it is:

<img width="1249" alt="Screenshot 2022-07-27 at 14 28 33" src="https://user-images.githubusercontent.com/24208746/181225705-db2421b5-3344-4d60-ae8a-013a82491a73.png">

So, for some reason, the server generated curve differs from client's one in some decimal points of calculations. As an easy fix, maybe we can make decimal precision a bit smaller without visual degradation?

    "next": "12.2.3",
    "react": "18.2.0",

**Comment by phamfoo** [comment]
I couldn't reproduce this on my machine. Could you provide a minimal repro?

**Comment by phamfoo** [comment]
Hi @max-frai, I just published a new version (0.3.1), now everything is rounded with `toFixed(4)`. Can you give it a try?
