### ISSUE TITLE
left corner error

### ISSUE THREAD

**Issue by longnguyen245** [tienphaw/figma-squircle#3]
The left edge has curved corners that are not as smooth as the right edge

![image](https://user-images.githubusercontent.com/87322951/213885608-2877f39e-b438-4c59-82c6-acf7255eab3c.png)
lelf corner

![image](https://user-images.githubusercontent.com/87322951/213885623-6514c43f-57f5-4b8e-854d-3818d713753d.png)
right corner

**Comment by nguyenvanlongweb** [comment]
sorry i created this problem, it seems the problem is with my monitor. help me delete this issue, thanks
