### ISSUE TITLE
Example with images

### ISSUE THREAD

**Issue by kierangillen** [tienphaw/figma-squircle#4]
Are there examples of the package being used to wrap images? For example if I wanted the following effect?

<img width="480" alt="Screenshot 2023-10-18 at 10 02 54 PM" src="https://github.com/phamfoo/figma-squircle/assets/21182806/42bbc9c3-5667-40a9-aa53-6e43809514f2">

Thank you!

**Comment by phamfoo** [comment]
Have you tried using `clip-path`? https://github.com/phamfoo/figma-squircle?tab=readme-ov-file#usage
